export const facultyCoursePrefix: { [key: string]: string } = {
	AB: 'Arabic',
	AF: 'Arts Faculty',
	AN: 'Anthropology',
	AR: 'Archaeology and Heritage Studies',
	AS: 'Astronomy',
	BF: 'Foundations',
	BI: 'Biology',
	BU: 'Business',
	CC: 'Criminology',
	CH: 'Chemistry',
	CL: 'Classical Studies',
	CP: 'Computer Science',
	CS: 'Communication Studies',
	DD: 'Game Design and Development',
	DH: 'Digital Humanities',
	EC: 'Economics',
	EM: 'Education minor',
	EN: 'English',
	ES: 'Environmental Science',
	EU: 'Bachelor of Education',
	FR: 'French',
	FS: 'Film Studies',
	GC: 'Christian Studies and Global Citizenship',
	GG: 'Geography',
	GL: 'Geology',
	GM: 'German',
	GS: 'Global Studies',
	GR: 'Greek',
	HD: 'Health Administration',
	HE: 'Health Sciences',
	HI: 'History',
	HN: 'Human Biology',
	HP: 'History and Philosophy of Science',
	HR: 'Human Rights and Human Diversity',
	HS: 'Health Studies',
	ID: 'Indigenous Studies',
	IT: 'Italian',
	KP: 'Kinesiology and Physical Education',
	KS: 'Cultural Studies',
	LA: 'Latin',
	LL: 'Languages and Literatures',
	LY: 'Law and Society',
	OL: 'Leadership',
	MA: 'Mathematics',
	MB: 'Business Technology Management',
	MI: 'Mediterranean Studies',
	ML: 'Medieval and Medievalism Studies',
	MX: 'Media Studies',
	MU: 'Music',
	MZ: 'Muslim Studies',
	NO: 'North American Studies',
	PP: 'Philosophy',
	PC: 'Physics',
	PD: 'Policing',
	PO: 'Political Science',
	PS: 'Psychology',
	RE: 'Religion and Culture',
	SC: 'Science',
	SE: 'Social Entrepreneurship',
	SL: 'Social Welfare',
	ST: 'Statistics',
	SY: 'Sociology',
	SP: 'Spanish',
	UU: 'Interdisciplinary',
	UX: 'User Experience Design',
	YC: "Youth and Children's Studies",
	DATA: 'Data Science',
	DMJN: 'Digital Media and Journalism',
	ENTR: 'Entrepreneurship',
	GESC: 'Geography and Environmental Studies',
	UNDC: 'Global Crime and Justice',
	INED: 'International Education Studies',
	WORK: 'Labour Studies and Career Development',
	SAFE: 'Public Safety',
	SOJE: 'Social and Environmental Justice'
}
