export const disciplineCodes: { [key: string]: string } = {
    "Arabic": "AB",
    "Arts Faculty": "AF",
    "Anthropology": "AN",
    "Archaeology and Heritage Studies": "AR",
    "Astronomy": "AS",
    "Foundations": "BF",
    "Biology": "BI",
    "Business": "BU",
    "Criminology": "CC",
    "Chemistry": "CH",
    "Classical Studies": "CL",
    "Computer Science": "CP",
    "Communication Studies": "CS",
    "Game Design and Development": "DD",
    "Digital Humanities": "DH",
    "Economics": "EC",
    "Education minor": "EM",
    "English": "EN",
    "Environmental Science": "ES",
    "Bachelor of Education": "EU",
    "French": "FR",
    "Film Studies": "FS",
    "Christian Studies and Global Citizenship": "GC",
    "Geography": "GG",
    "Geology": "GL",
    "German": "GM",
    "Global Studies": "GS",
    "Greek": "GR",
    "Health Administration": "HD",
    "Health Sciences": "HE",
    "History": "HI",
    "Human Biology": "HN",
    "History and Philosophy of Science": "HP",
    "Human Rights and Human Diversity": "HR",
    "Health Studies": "HS",
    "Indigenous Studies": "ID",
    "Italian": "IT",
    "Kinesiology and Physical Education": "KP",
    "Cultural Studies": "KS",
    "Latin": "LA",
    "Languages and Literatures": "LL",
    "Law and Society": "LY",
    "Leadership": "OL",
    "Mathematics": "MA",
    "Business Technology Management": "MB",
    "Mediterranean Studies": "MI",
    "Medieval and Medievalism Studies": "ML",
    "Media Studies": "MX",
    "Music": "MU",
    "Muslim Studies": "MZ",
    "North American Studies": "NO",
    "Philosophy": "PP",
    "Physics": "PC",
    "Policing": "PD",
    "Political Science": "PO",
    "Psychology": "PS",
    "Religion and Culture": "RE",
    "Science": "SC",
    "Social Entrepreneurship": "SE",
    "Social Welfare": "SL",
    "Statistics": "ST",
    "Sociology": "SY",
    "Spanish": "SP",
    "Interdisciplinary": "UU",
    "User Experience Design": "UX",
    "Youth and Children's Studies": "YC",
    "Data Science": "DATA",
    "Digital Media and Journalism": "DMJN",
    "Entrepreneurship": "ENTR",
    "Geography and Environmental Studies": "GESC",
    "Global Crime and Justice": "UNDC",
    "International Education Studies": "INED",
    "Labour Studies and Career Development": "WORK",
    "Public Safety": "SAFE",
    "Social and Environmental Justice": "SOJE"
}