export const programOptions = [
    "Accounting (Graduate Diploma)",
    "Ancient Studies (BA)",
    "Anthropology (BA in Combination)",
    "Applied Computing (MAC)",
    "Applied Health Sciences (BASc)",
    "Applied Mathematics (Option)",
    "Applied Politics (MAP)",
    "Applied Social Research (Option)",
    "Arabic (Minor)",
    "Archaeology and Heritage Studies (BA)",
    "Arts Degree (BA) + Business Administration (MBA) with Co-op",
    "Arts Degree (BA) + Master’s Degree (MA or MAP)",
    "Biochemistry and Biotechnology (BSc)",
    "Biological and Chemical Sciences (PhD)",
    "Biology (BA)",
    "Biology (BSc)",
    "Business Administration (BBA)",
    "Business Administration (BBA) + Computer Science (BCS), University of Waterloo",
    "Business Administration (BBA) + Computer Science (BSc)",
    "Business Administration (BBA) + Financial Mathematics (BA)",
    "Business Administration (BBA) + Mathematics (BMath), University of Waterloo",
    "Business Administration (Diploma)",
    "Business Administration (MBA)",
    "Business Economics (MABE)",
    "Business Technology Management (BTM)",
    "Chamber Music (Diploma)",
    "Chemistry (BSc)",
    "Chemistry (MSc)",
    "Chemistry and Physics (BSc)",
    "Christianity, Interfaith Dialogue, and Community Engagement (BA)",
    "Communication Studies (BA)",
    "Communication Studies (MA)",
    "Community Engagement (Option)",
    "Community Music (BMus)",
    "Community Music (MA)",
    "Computer Science (BA in Combination), Milton",
    "Computer Science (BA), Waterloo or Brantford",
    "Computer Science (BSc), Milton",
    "Computer Science (BSc), Waterloo",
    "Computer Science (Certificate)",
    "Computer Science and Physics (BSc)",
    "Creative Writing (Minor)",
    "Criminology (BA)",
    "Criminology (MA)",
    "Criminology and Policing (BA)",
    "Cultural Analysis and Social Theory (MA)",
    "Cultural Studies (BA in Combination)",
    "Data Science (BSc)",
    "Digital Humanities (Minor)",
    "Digital Humanities (Option)",
    "Economics (BA)",
    "Economics and Accounting (BA)",
    "Economics and Data Analytics (BA)",
    "Economics and Financial Management (BA)",
    "Education (BEd)",
    "Education (MEd)",
    "Education (Minor)",
    "English (BA), Brantford",
    "English (BA), Waterloo",
    "English and Film Studies (MA)",
    "English and Film Studies (PhD)",
    "Entrepreneurship Core (Option)",
    "Environmental Science (BSc)",
    "Environmental Studies (BA)",
    "Film Production (Option)",
    "Film Studies (BA)",
    "Finance (MFin)",
    "Finance (MFin) and Management Analytics (MSc) Double Degree",
    "Financial Mathematics (BA)",
    "Financial Mathematics (BSc)",
    "French (BA)",
    "Game Design and Development (BA)",
    "Geography (BA)",
    "Geography (BSc)",
    "Geography (MA)",
    "Geography (MES)",
    "Geography (MSc)",
    "Geography (PhD)",
    "Geomatics (Option)",
    "German (Minor)",
    "Global Crime and Justice (Certificate)",
    "Global Governance (PhD)",
    "Global Studies (BA)",
    "Global Studies / Human Rights (BA) + International Development (MA), University of Sussex",
    "Health Management (BA)",
    "Health Sciences (BSc)",
    "Health Sciences (MSc)",
    "Health Studies (BA)",
    "Health Studies (BA) + Public Health / Global Health (MSc), Brighton and Sussex Medical School",
    "History (BA), Brantford",
    "History (BA), Waterloo",
    "History (MA)",
    "History (PhD)",
    "History and Philosophy of Science (Minor)",
    "Honours Science (BSc)",
    "Human Relationships (PhD)",
    "Human Rights (BA)",
    "Indigenous Studies (BA in Combination)",
    "Integrative Biology (MSc)",
    "Intercultural Understanding (Option)",
    "International Development (Option)",
    "International Education Studies (BA)",
    "International Policy (Option)",
    "International Public Policy (MIPP)",
    "Issue Advocacy (Option)",
    "Italian (Minor)",
    "Kinesiology (BKin)",
    "Kinesiology (MSc)",
    "Kinesiology (PhD)",
    "Languages (BA)",
    "Law (LLB), University of Sussex + Arts Degree (BA)",
    "Law (LLB), University of Sussex + Science Degree (BSc)",
    "Law (Option)",
    "Law and Society (BA)",
    "Leadership (Option and Minor)",
    "Legal Studies (Option)",
    "Management (MSc)",
    "Management (Option)",
    "Management (PhD)",
    "Management Analytics (MSc)",
    "Master of Divinity (MDiv)",
    "Mathematical and Statistical Modelling (PhD)",
    "Mathematics (BA)",
    "Mathematics (BSc)",
    "Mathematics (MSc)",
    "Media Studies (Option)",
    "Medieval and Medievalism Studies (BA in Combination)",
    "Music (BMus)",
    "Music (PhD)",
    "Music Therapy (BMT)",
    "Music Therapy (MMT)",
    "Music: Collaboration, Curation, and Creative Performance (MMus)",
    "Muslim Studies (Option)",
    "Navigating the Music Industry Ecosystem (Certificate)",
    "North American Studies (BA in Combination)",
    "Opera (Diploma)",
    "Philosophy (BA)",
    "Policing (BA in Combination)",
    "Policing (BA)",
    "Political Science (BA)",
    "Practical Ethics and Society (Option)",
    "Professional Writing (Minor)",
    "Psychology (BA), Brantford",
    "Psychology (BA), Milton",
    "Psychology (BA), Waterloo",
    "Psychology (BSc), Brantford",
    "Psychology (BSc), Waterloo",
    "Psychology (MA)",
    "Psychology (MSc)",
    "Psychology (PhD)",
    "Psychology and Neuroscience (BSc)",
    "Public History (Minor)",
    "Public Policy (Minor)",
    "Public Safety (BA)",
    "Public Safety (Graduate Diploma)",
    "Public Safety (MPS)",
    "Religion and Culture (BA)",
    "Religion, Culture and Global Justice (MA)",
    "Religious Studies (PhD)",
    "Social Entrepreneurship (Option)",
    "Social Innovation (Minor)",
    "Social Justice and Community Engagement (MA)",
    "Social Work (BSW)",
    "Social Work (MSW)",
    "Social Work (PhD)",
    "Sociology (BA)",
    "Spanish (BA in Combination)",
    "Spiritual Care and Psychotherapy (Graduate Diploma)",
    "Spiritual Care and Psychotherapy (MA)",
    "Spirituality and Global Music (Minor)",
    "Statistics (Minor)",
    "Sustainability (Option)",
    "Teaching (Option)",
    "Theology and Divinity: Spiritual Care and Psychotherapy",
    "User Experience Design (BDes)",
    "User Experience Design (MSc)",
    "Women and Gender Studies (BA in Combination)",
    "Writing for Career and Community (Minor)",
    "Youth and Children: Texts and Contexts (Minor)",
    "Youth and Children’s Studies (BA)",
    "Other"
];