    export const programOptions = [
    { value: "Other", label: "Other" },
    { value: "Accounting (Graduate Diploma)", label: "Accounting (Graduate Diploma)" },
    { value: "Ancient Studies (BA)", label: "Ancient Studies (BA)" },
    { value: "Anthropology (BA in Combination)", label: "Anthropology (BA in Combination)" },
    { value: "Applied Computing (MAC)", label: "Applied Computing (MAC)" },
    { value: "Applied Health Sciences (BASc)", label: "Applied Health Sciences (BASc)" },
    { value: "Applied Mathematics (Option)", label: "Applied Mathematics (Option)" },
    { value: "Applied Politics (MAP)", label: "Applied Politics (MAP)" },
    { value: "Applied Social Research (Option)", label: "Applied Social Research (Option)" },
    { value: "Arabic (Minor)", label: "Arabic (Minor)" },
    { value: "Archaeology and Heritage Studies (BA)", label: "Archaeology and Heritage Studies (BA)" },
    { value: "Arts Degree (BA) + Business Administration (MBA) with Co-op", label: "Arts Degree (BA) + Business Administration (MBA) with Co-op" },
    { value: "Arts Degree (BA) + Master’s Degree (MA or MAP)", label: "Arts Degree (BA) + Master’s Degree (MA or MAP)" },
    { value: "Biochemistry and Biotechnology (BSc)", label: "Biochemistry and Biotechnology (BSc)" },
    { value: "Biological and Chemical Sciences (PhD)", label: "Biological and Chemical Sciences (PhD)" },
    { value: "Biology (BA)", label: "Biology (BA)" },
    { value: "Biology (BSc)", label: "Biology (BSc)" },
    { value: "Business Administration (BBA)", label: "Business Administration (BBA)" },
    { value: "Business Administration (BBA) + Computer Science (BCS), University of Waterloo", label: "Business Administration (BBA) + Computer Science (BCS), University of Waterloo" },
    { value: "Business Administration (BBA) + Computer Science (BSc)", label: "Business Administration (BBA) + Computer Science (BSc)" },
    { value: "Business Administration (BBA) + Financial Mathematics (BA)", label: "Business Administration (BBA) + Financial Mathematics (BA)" },
    { value: "Business Administration (BBA) + Mathematics (BMath), University of Waterloo", label: "Business Administration (BBA) + Mathematics (BMath), University of Waterloo" },
    { value: "Business Administration (Diploma)", label: "Business Administration (Diploma)" },
    { value: "Business Administration (MBA)", label: "Business Administration (MBA)" },
    { value: "Business Economics (MABE)", label: "Business Economics (MABE)" },
    { value: "Business Technology Management (BTM)", label: "Business Technology Management (BTM)" },
    { value: "Chamber Music (Diploma)", label: "Chamber Music (Diploma)" },
    { value: "Chemistry (BSc)", label: "Chemistry (BSc)" },
    { value: "Chemistry (MSc)", label: "Chemistry (MSc)" },
    { value: "Chemistry and Physics (BSc)", label: "Chemistry and Physics (BSc)" },
    { value: "Christianity, Interfaith Dialogue, and Community Engagement (BA)", label: "Christianity, Interfaith Dialogue, and Community Engagement (BA)" },
    { value: "Communication Studies (BA)", label: "Communication Studies (BA)" },
    { value: "Communication Studies (MA)", label: "Communication Studies (MA)" },
    { value: "Community Engagement (Option)", label: "Community Engagement (Option)" },
    { value: "Community Music (BMus)", label: "Community Music (BMus)" },
    { value: "Community Music (MA)", label: "Community Music (MA)" },
    { value: "Computer Science (BA in Combination), Milton", label: "Computer Science (BA in Combination), Milton" },
    { value: "Computer Science (BA), Waterloo or Brantford", label: "Computer Science (BA), Waterloo or Brantford" },
    { value: "Computer Science (BSc), Milton", label: "Computer Science (BSc), Milton" },
    { value: "Computer Science (BSc), Waterloo", label: "Computer Science (BSc), Waterloo" },
    { value: "Computer Science (Certificate)", label: "Computer Science (Certificate)" },
    { value: "Computer Science and Physics (BSc)", label: "Computer Science and Physics (BSc)" },
    { value: "Creative Writing (Minor)", label: "Creative Writing (Minor)" },
    { value: "Criminology (BA)", label: "Criminology (BA)" },
    { value: "Criminology (MA)", label: "Criminology (MA)" },
    { value: "Criminology and Policing (BA)", label: "Criminology and Policing (BA)" },
    { value: "Cultural Analysis and Social Theory (MA)", label: "Cultural Analysis and Social Theory (MA)" },
    { value: "Cultural Studies (BA in Combination)", label: "Cultural Studies (BA in Combination)" },
    { value: "Data Science (BSc)", label: "Data Science (BSc)" },
    { value: "Digital Humanities (Minor)", label: "Digital Humanities (Minor)" },
    { value: "Digital Humanities (Option)", label: "Digital Humanities (Option)" },
    { value: "Economics (BA)", label: "Economics (BA)" },
    { value: "Economics and Accounting (BA)", label: "Economics and Accounting (BA)" },
    { value: "Economics and Data Analytics (BA)", label: "Economics and Data Analytics (BA)" },
    { value: "Economics and Financial Management (BA)", label: "Economics and Financial Management (BA)" },
    { value: "Education (BEd)", label: "Education (BEd)" },
    { value: "Education (MEd)", label: "Education (MEd)" },
    { value: "Education (Minor)", label: "Education (Minor)" },
    { value: "English (BA), Brantford", label: "English (BA), Brantford" },
    { value: "English (BA), Waterloo", label: "English (BA), Waterloo" },
    { value: "English and Film Studies (MA)", label: "English and Film Studies (MA)" },
    { value: "English and Film Studies (PhD)", label: "English and Film Studies (PhD)" },
    { value: "Entrepreneurship Core (Option)", label: "Entrepreneurship Core (Option)" },
    { value: "Environmental Science (BSc)", label: "Environmental Science (BSc)" },
    { value: "Environmental Studies (BA)", label: "Environmental Studies (BA)" },
    { value: "Film Production (Option)", label: "Film Production (Option)" },
    { value: "Film Studies (BA)", label: "Film Studies (BA)" },
    { value: "Finance (MFin)", label: "Finance (MFin)" },
    { value: "Finance (MFin) and Management Analytics (MSc) Double Degree", label: "Finance (MFin) and Management Analytics (MSc) Double Degree" },
    { value: "Financial Mathematics (BA)", label: "Financial Mathematics (BA)" },
    { value: "Financial Mathematics (BSc)", label: "Financial Mathematics (BSc)" },
    { value: "French (BA)", label: "French (BA)" },
    { value: "Game Design and Development (BA)", label: "Game Design and Development (BA)" },
    { value: "Geography (BA)", label: "Geography (BA)" },
    { value: "Geography (BSc)", label: "Geography (BSc)" },
    { value: "Geography (MA)", label: "Geography (MA)" },
    { value: "Geography (MES)", label: "Geography (MES)" },
    { value: "Geography (MSc)", label: "Geography (MSc)" },
    { value: "Geography (PhD)", label: "Geography (PhD)" },
    { value: "Geomatics (Option)", label: "Geomatics (Option)" },
    { value: "German (Minor)", label: "German (Minor)" },
    { value: "Global Crime and Justice (Certificate)", label: "Global Crime and Justice (Certificate)" },
    { value: "Global Governance (PhD)", label: "Global Governance (PhD)" },
    { value: "Global Studies (BA)", label: "Global Studies (BA)" },
    { value: "Global Studies / Human Rights (BA) + International Development (MA), University of Sussex", label: "Global Studies / Human Rights (BA) + International Development (MA), University of Sussex" },
    { value: "Health Management (BA)", label: "Health Management (BA)" },
    { value: "Health Sciences (BSc)", label: "Health Sciences (BSc)" },
    { value: "Health Sciences (MSc)", label: "Health Sciences (MSc)" },
    { value: "Health Studies (BA)", label: "Health Studies (BA)" },
    { value: "Health Studies (BA) + Public Health / Global Health (MSc), Brighton and Sussex Medical School", label: "Health Studies (BA) + Public Health / Global Health (MSc), Brighton and Sussex Medical School" },
    { value: "History (BA), Brantford", label: "History (BA), Brantford" },
    { value: "History (BA), Waterloo", label: "History (BA), Waterloo" },
    { value: "History (MA)", label: "History (MA)" },
    { value: "History (PhD)", label: "History (PhD)" },
    { value: "History and Philosophy of Science (Minor)", label: "History and Philosophy of Science (Minor)" },
    { value: "Honours Science (BSc)", label: "Honours Science (BSc)" },
    { value: "Human Relationships (PhD)", label: "Human Relationships (PhD)" },
    { value: "Human Rights (BA)", label: "Human Rights (BA)" },
    { value: "Indigenous Studies (BA in Combination)", label: "Indigenous Studies (BA in Combination)" },
    { value: "Integrative Biology (MSc)", label: "Integrative Biology (MSc)" },
    { value: "Intercultural Understanding (Option)", label: "Intercultural Understanding (Option)" },
    { value: "International Development (Option)", label: "International Development (Option)" },
    { value: "International Education Studies (BA)", label: "International Education Studies (BA)" },
    { value: "International Policy (Option)", label: "International Policy (Option)" },
    { value: "International Public Policy (MIPP)", label: "International Public Policy (MIPP)" },
    { value: "Issue Advocacy (Option)", label: "Issue Advocacy (Option)" },
    { value: "Italian (Minor)", label: "Italian (Minor)" },
    { value: "Kinesiology (BKin)", label: "Kinesiology (BKin)" },
    { value: "Kinesiology (MSc)", label: "Kinesiology (MSc)" },
    { value: "Kinesiology (PhD)", label: "Kinesiology (PhD)" },
    { value: "Languages (BA)", label: "Languages (BA)" },
    { value: "Law (LLB), University of Sussex + Arts Degree (BA)", label: "Law (LLB), University of Sussex + Arts Degree (BA)" },
    { value: "Law (LLB), University of Sussex + Science Degree (BSc)", label: "Law (LLB), University of Sussex + Science Degree (BSc)" },
    { value: "Law (Option)", label: "Law (Option)" },
    { value: "Law and Society (BA)", label: "Law and Society (BA)" },
    { value: "Leadership (Option and Minor)", label: "Leadership (Option and Minor)" },
    { value: "Legal Studies (Option)", label: "Legal Studies (Option)" },
    { value: "Management (MSc)", label: "Management (MSc)" },
    { value: "Management (Option)", label: "Management (Option)" },
    { value: "Management (PhD)", label: "Management (PhD)" },
    { value: "Management Analytics (MSc)", label: "Management Analytics (MSc)" },
    { value: "Master of Divinity (MDiv)", label: "Master of Divinity (MDiv)" },
    { value: "Mathematical and Statistical Modelling (PhD)", label: "Mathematical and Statistical Modelling (PhD)" },
    { value: "Mathematics (BA)", label: "Mathematics (BA)" },
    { value: "Mathematics (BSc)", label: "Mathematics (BSc)" },
    { value: "Mathematics (MSc)", label: "Mathematics (MSc)" },
    { value: "Media Studies (Option)", label: "Media Studies (Option)" },
    { value: "Medieval and Medievalism Studies (BA in Combination)", label: "Medieval and Medievalism Studies (BA in Combination)" },
    { value: "Music (BMus)", label: "Music (BMus)" },
    { value: "Music (PhD)", label: "Music (PhD)" },
    { value: "Music Therapy (BMT)", label: "Music Therapy (BMT)" },
    { value: "Music Therapy (MMT)", label: "Music Therapy (MMT)" },
    { value: "Music: Collaboration, Curation, and Creative Performance (MMus)", label: "Music: Collaboration, Curation, and Creative Performance (MMus)" },
    { value: "Muslim Studies (Option)", label: "Muslim Studies (Option)" },
    { value: "Navigating the Music Industry Ecosystem (Certificate)", label: "Navigating the Music Industry Ecosystem (Certificate)" },
    { value: "North American Studies (BA in Combination)", label: "North American Studies (BA in Combination)" },
    { value: "Opera (Diploma)", label: "Opera (Diploma)" },
    { value: "Philosophy (BA)", label: "Philosophy (BA)" },
    { value: "Policing (BA in Combination)", label: "Policing (BA in Combination)" },
    { value: "Policing (BA)", label: "Policing (BA)" },
    { value: "Political Science (BA)", label: "Political Science (BA)" },
    { value: "Practical Ethics and Society (Option)", label: "Practical Ethics and Society (Option)" },
    { value: "Professional Writing (Minor)", label: "Professional Writing (Minor)" },
    { value: "Psychology (BA), Brantford", label: "Psychology (BA), Brantford" },
    { value: "Psychology (BA), Milton", label: "Psychology (BA), Milton" },
    { value: "Psychology (BA), Waterloo", label: "Psychology (BA), Waterloo" },
    { value: "Psychology (BSc), Brantford", label: "Psychology (BSc), Brantford" },
    { value: "Psychology (BSc), Waterloo", label: "Psychology (BSc), Waterloo" },
    { value: "Psychology (MA)", label: "Psychology (MA)" },
    { value: "Psychology (MSc)", label: "Psychology (MSc)" },
    { value: "Psychology (PhD)", label: "Psychology (PhD)" },
    { value: "Psychology and Neuroscience (BSc)", label: "Psychology and Neuroscience (BSc)" },
    { value: "Public History (Minor)", label: "Public History (Minor)" },
    { value: "Public Policy (Minor)", label: "Public Policy (Minor)" },
    { value: "Public Safety (BA)", label: "Public Safety (BA)" },
    { value: "Public Safety (Graduate Diploma)", label: "Public Safety (Graduate Diploma)" },
    { value: "Public Safety (MPS)", label: "Public Safety (MPS)" },
    { value: "Religion and Culture (BA)", label: "Religion and Culture (BA)" },
    { value: "Religion, Culture and Global Justice (MA)", label: "Religion, Culture and Global Justice (MA)" },
    { value: "Religious Studies (PhD)", label: "Religious Studies (PhD)" },
    { value: "Social Entrepreneurship (Option)", label: "Social Entrepreneurship (Option)" },
    { value: "Social Innovation (Minor)", label: "Social Innovation (Minor)" },
    { value: "Social Justice and Community Engagement (MA)", label: "Social Justice and Community Engagement (MA)" },
    { value: "Social Work (BSW)", label: "Social Work (BSW)" },
    { value: "Social Work (MSW)", label: "Social Work (MSW)" },
    { value: "Social Work (PhD)", label: "Social Work (PhD)" },
    { value: "Sociology (BA)", label: "Sociology (BA)" },
    { value: "Spanish (BA in Combination)", label: "Spanish (BA in Combination)" },
    { value: "Spiritual Care and Psychotherapy (Graduate Diploma)", label: "Spiritual Care and Psychotherapy (Graduate Diploma)" },
    { value: "Spiritual Care and Psychotherapy (MA)", label: "Spiritual Care and Psychotherapy (MA)" },
    { value: "Spirituality and Global Music (Minor)", label: "Spirituality and Global Music (Minor)" },
    { value: "Statistics (Minor)", label: "Statistics (Minor)" },
    { value: "Sustainability (Option)", label: "Sustainability (Option)" },
    { value: "Teaching (Option)", label: "Teaching (Option)" },
    { value: "Theology and Divinity: Spiritual Care and Psychotherapy", label: "Theology and Divinity: Spiritual Care and Psychotherapy" },
    { value: "User Experience Design (BDes)", label: "User Experience Design (BDes)" },
    { value: "User Experience Design (MSc)", label: "User Experience Design (MSc)" },
    { value: "Women and Gender Studies (BA in Combination)", label: "Women and Gender Studies (BA in Combination)" },
    { value: "Writing for Career and Community (Minor)", label: "Writing for Career and Community (Minor)" },
    { value: "Youth and Children: Texts and Contexts (Minor)", label: "Youth and Children: Texts and Contexts (Minor)" },
    { value: "Youth and Children’s Studies (BA)", label: "Youth and Children’s Studies (BA)" },
];  